# Generated by Django 3.2.7 on 2021-10-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(default='images/download.png', upload_to='images/')),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(default='images/download.png', upload_to='images/')),
                ('details', models.TextField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(related_name='weapon_attachments', to='weapons.Attachment')),
            ],
        ),
    ]
